version: "2.2"
services:
  jgw:
    image: intersystemsdc/extld:jgw
    hostname: jgw
    environment:
      - JAVA_GATEWAY
      - JVMARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    build:
      context: java
      dockerfile: Dockerfile
      args:
        IRIS_IMAGE: ${IRIS_IMAGE}
        JAVA_GATEWAY: ${JAVA_GATEWAY}
    restart: always
    ports:
      - ${JAVA_GATEWAY}:${JAVA_GATEWAY}
      - 5005:5005
    volumes:
      - ./data:/data
  iris:
    image: intersystemsdc/extld:iris
    hostname: iris
    build:
      context: iris
      dockerfile: Dockerfile
      args:
        IRIS_IMAGE: ${IRIS_IMAGE}
    ports:
      - 52773:52773
      - 51773:51773